// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdwrwuvvzhxqtbpygruz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkd3J3dXZ2emh4cXRicHlncnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzYzMzYsImV4cCI6MjA2NTc1MjMzNn0.CwMaf6JDhGZc2jOHUIh9Sh9W4rAyMeaZRkvk4Dszc88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);